<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers on chapters. -->

# Introduction {#intro}

Coal is the second most used fuel for electricity generation in the United States.  In 2017, approximately 30% of all electricity production was fueled by coal combustion [@energyinformationadministrationTableNetGeneration2018].  Although the percentage has fallen in recent years due to retirement of coal-fired plants and increases in natural gas and other energy sources, coal remains a main fuel for electricity. Coal combustion results in the production of the waste material, coal ash.

Coal ash is composed of fly ash, bottom ash, and flue gas desulfurized gypsum.  Fly ash is a fine powdery substance, comprised primarily of silica that is exhausted. It is produced during the combustion of finely ground coal and most is captured from the exhaust using electrostatics and scrubber systems.  Bottom ash is formed during the combustion of pulverized coal in boilers.  It ranges in size from fine sand to fine gravel and is grey to black in color.  Bottom ash is too large to be carried up the exhaust system and is collected in an ash hopper.  Flue gas desulfurized gypsum is not a direct product of coal combustion, but a product of the scrubber system to remove SO^2^ emissions from exhaust [@kiskuCharacterizationCoalFly2018; @messingerUnmannedAerialVehicles2016]. 

Physical and chemical properties of coal ash are determined by the geographical location where the raw coal was mined, the type of boiler, and the operating conditions of the power plant [@jayaranjanReuseOptionsCoal2014]. Fly ash is composed mainly of oxides such as $\mathrm{SiO_2}$, $\mathrm{Al_2O}$, $\mathrm{Fe_2O}$, $\mathrm{TiO_2}$, and $\mathrm{CaO}$.  All natural elements can be found in coal ash, trace elements include, As, Cd, Cr, Hg, Pb, Se, and Zn  [@greelyjr.EffectsSedimentContaining2014; @jayaranjanReuseOptionsCoal2014; @shaheenOpportunitiesChallengesUse2014]. Coal bottom ash consists of silicate, carbonate, aluminate, ferrous materials and several of heavy metals and metalloids. Like fly ash, the chemical composition of the bottom ash is dependent on the source of the raw coal, boiler type, and the refinement process of the raw coal [@jayaranjanReuseOptionsCoal2014]. 

Once produced and collected, coal ash, in many cases, is mixed with water to form a slurry and stored wet in settling ponds. These ponds are constructed either lined or unlined; open to the atmosphere or capped. The coal ash storage pond located at the Dan River Steam Station, was an open, unlined two-pond system where, the coal ash is pumped into one pond where it settles out of the water column, then pumped to a second pond for further settling before effluent is discharged into the river [@messingerUnmannedAerialVehicles2016]. In the US, of the approximately 120 Mt of coal ash is produced annually, 54% is disposed of in landfills or settling ponds [@americancoalashassociation2012CoalCombustion2012]. Possible catastrophic impoundment failures and chronic leaching from unlined impoundments, allow the mobilization of coal ash including their associated heavy metals into the environment where these metals may enter the food web directly or indirectly through microbially-mediated transformations [@cabralMethylmercuryDegradationPseudomonas2016; @deonarineEnvironmentalImpactsTennessee2013; @otterTrophicStatusMetal2012]. 

On February 2, 2014, two storm water drainage pipes located under a coal ash impoundment pond at the Duke Energy Dan River Steam Station near Eden, NC collapsed, releasing approximately 28,000 cubic yards of coal ash and about 27 million gallons of untreated ash wastewater into the Dan River [@lemlyDamageCostDan2015]. Following the spill, water and sediment was sampled from the river and Kerr Reservoir downstream of the spill to assess water quality and human health concerns. Test results show no constituents to be at levels exceeding safe limits in the water column  [@usepaEPAResponseDuke2014; @hesterbergAssessmentTraceelementImpacts2014]. Duke Energy dredged ash deposits at two locations along the river, but likely over 90% of the ash remains buried in river sediments or has been deposited into Kerr Lake [@ncdeqRapidResponseTimeline2014].  While the test results were encouraging for immediate water quality, the long-term concern is the effect of mobilization of coal ash constituents into the riverine food webs.

