# IDENTIFICATION AND CHARACTERIZATION OF HEAVY METAL TOLERANCE OF BACTERIA CULTURED FROM COAL ASH {#metal}

## Abstract

Coal ash, the residual material of coal combustion for electricity generation, contains heavy metals and other pollutants, is generally deposited into reservoir ponds for storage, although it may spill or leach into nearby water and possibly disrupt aquatic ecological communities. We identified and characterized the metal tolerance of bacteria isolated from a sample of coal ash from a coal ash pond located at the retired Dan River Steam Station in Eden, NC.  SSU rDNA extracted from isolated organisms was sequenced and isolates were predominantly identified as Bacillus and Arthrobacter spp. Isolates were grown in 50% nutrient broth amended with heavy metals commonly found in coal ash waste (As, Cd, Cr, Hg, Pb, Se, Zn), at environmentally relevant concentrations. Growth of coal ash isolates was compared to isolates cultured from coal ash free soil. Overall, isolates exhibited metal tolerance, but so did the soil isolates. 

## Introduction

Coal ash is a waste product generated from power plants that use coal to generate electricity. After the combustion process, the ash and other waste products are discharged as a slurry into a settling pond or lagoon. The water level in the pond is maintained by pumping surface water into a nearby water-source, usually a river. In North Carolina, 14 such coal ash ponds are maintained by Duke Energy  [REF]. The location of power plants near water sources is necessary for meeting water demands during the electricity generation process. Unlined and uncapped coal ash waste ponds therefore have the potential for leaching contaminants into the groundwater or spilling into nearby waterways possibly polluting drinking water and/or disrupting aquatic ecological communities [REF].  

On February 2, 2014, a coal ash pond located at the retired Dan River Steam Station near Eden, NC expelled approximately 39,000 tons of coal ash/water mixture into the Dan River of North Carolina due to an underground pipe collapse. The slurry coated the river bottom for XX km… Emptied in Kerr Lake. XX was dredged from the pond… [REF]

Physical and chemical properties of coal ash are determined by the geographical location where the raw coal was mined, the type of boiler, and the operating conditions of the power plant [@jayaranjanReuseOptionsCoal2014].  All natural elements can be found in coal ash including some trace elements such as arsenic, cadmium, chromium, mercury, lead, selenium, and zinc [@greelyjr.EffectsSedimentContaining2014; @jayaranjanReuseOptionsCoal2014].  Coal ash is wholly comprised of multiple waste products with differing chemical properties including fly ash, bottom ash, and byproducts of pollution mitigation processes [REF]. Fly ash is composed mainly of oxides such as, $\mathrm{SiO_2}$, $\mathrm{Al_2O}$, $\mathrm{Fe_2O}$ [@usepaFlyAshCoal2014]. Bottom ash consists of silicate, carbonate, aluminate, ferrous materials and high concentrations of several heavy metals and metalloids [@usepaBottomAshCoal2014]. 

Heavy metals are characterized by a density greater than 5 g/$\mathrm{cm^3}$, mostly transition elements, and play an important role as trace elements in biochemical reactions. These heavy metals, due to an incompletely filled d orbital, allow the cations to form complex compounds with the potential to be redox reactive. Heavy metal ions form unspecific complex compounds in the cell, leading to toxic effects. For example, $\mathrm{Hg^{2+}}$, $\mathrm{Cd^{2+}}$, and $\mathrm{Ag^{+}}$ form strong toxic complexes that are not conducive to any physiological function and are highly toxic. Trace metals such as $\mathrm{Zn^{2+}}$, $\mathrm{Ni^{2+}}$, and $\mathrm{Cu^{2+}}$ required for some functions are toxic at high concentrations. Therefore, the intracellular concentration of heavy metals must be controlled, and organisms have adapted heavy metal resistance strategies [REFs].  

Through the process of coal combustion, the coal ash is rendered sterile. Therefore, inocuation of coal ash occurs by natual processes including atmospheric deposition (rainfall, windblown particulates) into the pond. Opportunistic microorganisms adapt to the high concentration of heavy metals through resistance or metal detoxification. In addition to naturally occurring processes, anthropogenic perturbations such as coal ash spills result in altered environments in which microbes may adapt and mobilize coal ash consituents into foodwebs (ref?). Knowledge of the microbial community stucture and distribution is important to estimate the extent of biological mobility of these pollutants. Further, organisms which exhibit metal tolerance may warrant further investigation into their potential for bioremediation.

The objective of this study was to determine if a microbial community is viable and present in coal ash ponds, to identify taxa, and characterize the metal tolerance of isolated organisms. Previous studies have analyzed the microbial community of soils  amended with coal ash (e.g. [@klubekCharacterizationMicrobialAbundance1992]).  
No studies have determined the microbial community of coal ash alone. 
Preliminary work showed a small amount of DNA present in a coal ash sample from the Dan River Steam Station coal ash pond, but we were not able to amplifiy SSU rDNA from bacteria with universal prokaryotic primers, possibly due to contaminamnts present in the sample or low concentrations of bacterial DNA. In this study, we increased the abundance of microbes and their DNA by culturing and isolaing samples of coal ash, to ensure adequate amounts of DNA for analysis. 

### Objectives and hypotheses

**Objective 1: To determine the metal tolerance of bacteria isolated from coal ash collected from the Dan River impoundment site.**

*I hypothesize that microbial growth of bacterial isolates from pure coal ash collected at the Dan River Steam Station impoundment pond will be more tolerant to heavy metals than organisms isolated compared to a reference site (soil collected from Peabody Park on UNCG campus).*

**Objective 2: To identify isolated bacteria using qPCR amplification and rDNA sequencing. I seek to identify these taxa using qPCR amplification and rDNA sequencing to compare to the GenBank database.**

*I hypothesize novel organisms may be discovered which may have unique metal tolerance capabilities that may be useful for bioremediation.*

## Methods
### Pure culture isolation from coal ash
Samples of coal ash provided by our collaborator, Brian Williams of the Dan River Basin Association was taken directly from a coal ash retention pond at the retired Dan River Steam Station near Eden, NC. To culture isolated organisms, aliquots (0.5 g) of coal ash from the coal ash pond was added to six 50 mL conical tubes. 40 mL of filter sterilized (0.22 µm pore) Dan River water was added to three tubes and filter sterilized Dan River supplemented with 10% nutrient broth to the other three tubes.  Additionally, filter sterilized Dan River water alone was evaluated in triplicate to serve as a sterility control. Tubes were incubated at room temperature for 48 hours.  100 mL aliquots were removed from each culture for spread plate culturing and preserved in  cetyltrimethylammonium bromide (CTAB) for DNA sequencing. Unique colonies identified on spread plates were isolated and pure cultures maintained for heavy metal tolerance experimentation. Sediment samples collected from Peabody Park, UNCG campus, were isolated using the same protocol as above. 

### Heavy metal characterization
Optical density (OD), of liquid broth culture was employed to ascertain the growth of organisms; where growth is related to the increase in turbidity of a bacterial culture. OD, or absorbance, is a measure of light that is absorbed or scattered by cells within a culture. According to Beer’s law, absorbance is proportional to concentration [@ModelingMicrobialResponses] (McMeekin et al from modeling microbial responses in food). 
Metals tested include, arsenic, cadmium, chromium, mercury, lead, selenium and zinc. Stock concentrations of $\mathrm{Na_2HAsO_4}$, $\mathrm{CdCl_2}$, $\mathrm{CrCl_3}$, $\mathrm{HgCl_2}$, $\mathrm{PbCl_2}$, $\mathrm{Na_2SeO_3}$, and $\mathrm{ZnCl_2}$ were asceptically serially diluted to span at least two orders of magnitude greater and less than natural environmental concentrations for each metal, resulting in 5 concentration levels per metal [TABLE X]. 

```{r metals echo=FALSE}
metal_conc <- readxl::read_excel("data/metal_concentrations.xlsx")
```


| Concentration | As    | Cd    | Cr   | Hg    | Pb   | Se    | Zn   |
|:-------------:|:-----:|:-----:|:----:|:-----:|:----:|:-----:|:----:|
| 1             | 0.001 | 0.001 | 0.01 | 0.001 | 0.01 | 1     | 0.1  |
| 2             | 0.01  | 0.01  | 0.1  | 0.01  | 0.1  | 10    | 1    |
| 3             | 0.1   | 0.1   | 1    | 0.1   | 1    | 100   | 10   |
| 4             | 1     | 1     | 10   | 1     | 10   | 1000  | 100  |
| 5             | 10    | 10    | 100  | 10    | 100  | 10000 | 1000 |
Table (\#tab)

Metal stocks were prepared by dissolving each metal salt in sterile reverse osmosis deionized (RO/DI) water and subsequently diluted [NEED TABLE TO DESCRIBE GRAMS?]. To ensure a viable culture inoculum, sufficient volume of cells, and standardization for experimentation, each unique isolate was incubated in a 50% nutrient broth culture in a shaking water bath at 25C overnight until a density of 0.7 at 580 nm was reached. For each metal-isolate experiment, 100 L of 0.7 OD580 nm organism inoculum was added to 2.4 mL of 50% nutrient broth amended with 100 µL each concentration of metal in triplicate. For the control, 100 µL of RO/DI water was substituted for the metal spike in triplicate. Growth patterns were measured by absorbance at 580nm, and recorded at nine time points, approximately 0, 1, 2, 4, 8, 16, 24, 30, 36, and 48 hours post inoculation. 

### Isolate identification and phylogenetic analysis 
For each isolate, DNA was extracted using the CTAB method, amplified with 16S primers and sent to [SENT WHERE?] for sequencing [@stewartRapidCTABDNA1993]. Organism chromatogram data was evaluated and edited manually to optimize the DNA sequence. The FASTA files of sequences were imported into the Molecular Evolutionary Genetics Analysis version 7.0 (MEGA7) [@kumarMEGA7MolecularEvolutionary2016]. Sequences were aligned using MUSCLE and manual adjustments [@edgarMUSCLEMultipleSequence2004]. The resulting aligned sequences were then subjected to phylogenetic tree analysis using MEGA7. The maximum likelihood tree was computed using MEGA7 using the Jukes-Cantor model [@jukesEvolutionProteinMolecules1969]. The bootstrap consensus tree was inferred from 1000 replicates. Initial trees with a greater log likelihood value were calculated by applying Neighbor-Join and BioNJ algorithms to a matrix of pairwise distances estimated using the Maximum Composite Likelihood approach.   

### Statistical analyses

Due to the inherent randomness of biological systems, standard statistical models will easily predict differences between bacterial growth curves [REF linear models paper]. The challenge lies in determining truly different growth curves from the similar curves differing only as a result of random fluctuations in growth. The approach taken in this study consists of calculating the slopes, or growth rates, for each bacterial growth curve using the method of ordinary least squares regression. The measurement in this study consists of OD with respect to time, therefore, growth rate should be understood as OD rate. The aim of this experiment is to compare different isolates’ growth with respect to common factors; concentration and time, and not modelling the empirical growth as such. Each slope was computed by fitting a linear regression over the linear range of growth of each isolate, at time points 4 to 7. To determine metal tolerance, significance of the coefficients by 95% confidence interval based on t-test… was performed to determine significance of each isolate-metal-concentration interaction compared to its control.  Isolates were deemed metal tolerant if the growth rate of one or more concentrations of metal significantly exceeded that of the control.   Experiments were excluded from analysis if there was no growth observed in the control where the slope was not significantly different from 0.
To determine the growth rate a spline regression was performed for each isolate metal and concentration. Each Spline regression to d
Because the data were not normally distributed (Shapiro-Wilk test for normality Need the p value) even after various transformations were tried, only nonparametric analyses were used throughout this study.

## Results
26 total isolates of unknown microorganisms were cultured from the samples; the coal ash without added nutrients and 14 from the coal ash with nutrients sample, and were sequenced. Sequences were aligned and a phylogenetic tree was constructed (Figure 4). Sequences of isolates were compared to the GenBank database. When exposed to heavy metal, isolates generally grew well in all but the highest metal concentrations. There was little difference between coal ash isolates and control isolates. Growth pattern of a few isolates suggested metal dependency (Figure 5). Absorbance results from ________were eliminated for subsequent calculations, since no growth curve was observed along the study period.

Isolates that did not grow and were excluded from further analysis. In some cases, the control did not grow, but other concentrations did. These isolates were excluded from analysis because there was no control in the experiment. 
SI 2 a soil isolate exhibited slow growth. The protocol of the study did not capture the growth of this isolate. Figure X Growth was not observed until the end of the reading time points therefore data was not obtained.  
Since only one reading was taken of each tube at each time point, repeatability was not ascertained. While each test tube was inoculated from the same culture, random fluctuations of growth were discovered. Look for others…. Such that one of the three showed faster growth than other ones in the experiment increasing the average and something about points that influence results. Influential points. NO 22 and SI2 slow growing, needed more time. ANOVA tukey? Comparison of growth for each metal? For each isolate? Post hoc analysis 

The Bayesian, maximum likelihood, and neighbor joining phylogenies yielded very similar topologies
Optimal topology
taxa
This phylogeny suggests that? 
Dominated by … list characteristics of the clade?? Where the organisms are usually found list clades habitat etc. 
One taxon… not found in the database
Diversity of organisms culturable from coal ash
Quickly deployed easily grown and maintained .
Rooted as outgroup? The novel one? Or something else? Research proper roots for the phylogeny ask parke?

Discussion
Although there were some significant seasonal differences, the magnitude of these
differences was small.
Selective pressure from culturing – only able to grow in lab very small proportion of what is really there. Easily grown in lab


## Discussion